#!/bin/sh

# Set these paths appropriately

BIN="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/bin"
CMD="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/cmd"
LIB="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
TAGGER=tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations
PARFILE=${LIB}/portuguese2.par

$TOKENIZER -p -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
