#!/bin/sh

# Set these paths appropriately

BIN="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/bin"
CMD="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/cmd"
LIB="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
