#!/bin/sh

# Set these paths appropriately

BIN="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/bin"
CMD="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/cmd"
LIB="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
