#!/bin/sh

# Set these paths appropriately

BIN="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/bin"
CMD="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/cmd"
LIB="/Users/abdelhak/Documents/Master-NLP-(IDMC)/Terminology-&-Ontologies/TERMSUITE_WORKSPACE/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
